In [1]:
import pandas as pd

In [9]:
data=pd.read_csv('doa1.csv')
data

,student_id,item_id,Q_matrix,t_all,t_e,t_s,s_e,diff,evaluate,correct,pred
0,96,445,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.18913830816745758, 0.18913830816745758, 0.1...","[0.13853970170021057, 0.13853970170021057, 0.1...","[0.2190929502248764, 0.2190929502248764, 0.219...","[0.1850096434354782, 0.1850096434354782, 0.185...","[0.44314324855804443, 0.44313690066337585, 0.4...",[1.0],0,0
1,18,114,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.32720625400543213, 0.32720625400543213, 0.3...","[0.3269776999950409, 0.3269776999950409, 0.326...","[0.30763840675354004, 0.30763840675354004, 0.3...","[0.5655176639556885, 0.5655176639556885, 0.565...","[0.4433152973651886, 0.4432937800884247, 0.443...",[1.0],0,0
2,32,175,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.3055531680583954, 0.3055531680583954, 0.305...","[0.09325031191110611, 0.09325031191110611, 0.0...","[0.42239001393318176, 0.42239001393318176, 0.4...","[0.39525118470191956, 0.39525118470191956, 0.3...","[0.44333550333976746, 0.4433133900165558, 0.44...",[1.0],0,0
3,99,457,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.5710980892181396, 0.5710980892181396, 0.571...","[0.6747953295707703, 0.6747953295707703, 0.674...","[0.5025438070297241, 0.5025438070297241, 0.502...","[0.6662260293960571, 0.6662260293960571, 0.666...","[0.44324880838394165, 0.4432337284088135, 0.44...",[1.0],1,1
4,106,483,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.3991096019744873, 0.3991096019744873, 0.399...","[0.15492047369480133, 0.15492047369480133, 0.1...","[0.5391915440559387, 0.5391915440559387, 0.539...","[0.4333671033382416, 0.4333671033382416, 0.433...","[0.44319283962249756, 0.4431827664375305, 0.44...",[1.0],0,1
...,...,...,...,...,...,...,...,...,...,...,...
230,20,126,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.5050808787345886, 0.5050808787345886, 0.505...","[0.7373476028442383, 0.7373476028442383, 0.737...","[0.3471999764442444, 0.3471999764442444, 0.347...","[0.770522952079773, 0.770522952079773, 0.77052...","[0.443512499332428, 0.4434730112552643, 0.4434...",[1.0],0,1
231,73,343,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.32341212034225464, 0.32341212034225464, 0.3...","[0.3273879587650299, 0.3273879587650299, 0.327...","[0.3062048852443695, 0.3062048852443695, 0.306...","[0.5034056901931763, 0.5034056901931763, 0.503...","[0.4431690275669098, 0.44315993785858154, 0.44...",[1.0],0,0
232,97,447,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.5941956043243408, 0.5941956043243408, 0.594...","[0.739498496055603, 0.739498496055603, 0.73949...","[0.5203070640563965, 0.5203070640563965, 0.520...","[0.45930778980255127, 0.45930778980255127, 0.4...","[0.44315385818481445, 0.443146675825119, 0.443...",[1.0],0,1
233,118,555,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.5425879955291748, 0.5425879955291748, 0.542...","[0.532169759273529, 0.532169759273529, 0.53216...","[0.5576061010360718, 0.5576061010360718, 0.557...","[0.4346829950809479, 0.4346829950809479, 0.434...","[0.44313791394233704, 0.4431315064430237, 0.44...",[1.0],1,1
234,18,120,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.4509989619255066, 0.4509989619255066, 0.450...","[0.6773908734321594, 0.6773908734321594, 0.677...","[0.3191322088241577, 0.3191322088241577, 0.319...","[0.44336268305778503, 0.44336268305778503, 0.4...","[0.44326716661453247, 0.4432499408721924, 0.44...",[1.0],1,1

In [4]:
item=pd.read_csv('../../data/IRE_Comta/item.csv')
item

     item_id knowledge_code
0          1            [0]
1          2         [1, 0]
2          3         [2, 0]
3          4         [1, 0]
4          5         [1, 0]
..       ...            ...
465      590           [31]
466      591           [31]
467      592       [22, 25]
468      593       [22, 25]
469      594          [116]

[470 rows x 2 columns]

In [10]:
data_item=data.merge(item,how='left',left_on='item_id',right_on='item_id')
data_item

,student_id,item_id,Q_matrix,t_all,t_e,t_s,s_e,diff,evaluate,correct,pred,knowledge_code
0,96,445,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.18913830816745758, 0.18913830816745758, 0.1...","[0.13853970170021057, 0.13853970170021057, 0.1...","[0.2190929502248764, 0.2190929502248764, 0.219...","[0.1850096434354782, 0.1850096434354782, 0.185...","[0.44314324855804443, 0.44313690066337585, 0.4...",[1.0],0,0,[82]
1,18,114,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.32720625400543213, 0.32720625400543213, 0.3...","[0.3269776999950409, 0.3269776999950409, 0.326...","[0.30763840675354004, 0.30763840675354004, 0.3...","[0.5655176639556885, 0.5655176639556885, 0.565...","[0.4433152973651886, 0.4432937800884247, 0.443...",[1.0],0,0,[58]
2,32,175,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.3055531680583954, 0.3055531680583954, 0.305...","[0.09325031191110611, 0.09325031191110611, 0.0...","[0.42239001393318176, 0.42239001393318176, 0.4...","[0.39525118470191956, 0.39525118470191956, 0.3...","[0.44333550333976746, 0.4433133900165558, 0.44...",[1.0],0,0,"[52, 97]"
3,99,457,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.5710980892181396, 0.5710980892181396, 0.571...","[0.6747953295707703, 0.6747953295707703, 0.674...","[0.5025438070297241, 0.5025438070297241, 0.502...","[0.6662260293960571, 0.6662260293960571, 0.666...","[0.44324880838394165, 0.4432337284088135, 0.44...",[1.0],1,1,"[151, 152]"
4,106,483,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.3991096019744873, 0.3991096019744873, 0.399...","[0.15492047369480133, 0.15492047369480133, 0.1...","[0.5391915440559387, 0.5391915440559387, 0.539...","[0.4333671033382416, 0.4333671033382416, 0.433...","[0.44319283962249756, 0.4431827664375305, 0.44...",[1.0],0,1,"[78, 79]"
...,...,...,...,...,...,...,...,...,...,...,...,...
230,20,126,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.5050808787345886, 0.5050808787345886, 0.505...","[0.7373476028442383, 0.7373476028442383, 0.737...","[0.3471999764442444, 0.3471999764442444, 0.347...","[0.770522952079773, 0.770522952079773, 0.77052...","[0.443512499332428, 0.4434730112552643, 0.4434...",[1.0],0,1,NaN
231,73,343,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.32341212034225464, 0.32341212034225464, 0.3...","[0.3273879587650299, 0.3273879587650299, 0.327...","[0.3062048852443695, 0.3062048852443695, 0.306...","[0.5034056901931763, 0.5034056901931763, 0.503...","[0.4431690275669098, 0.44315993785858154, 0.44...",[1.0],0,0,"[132, 133, 134]"
232,97,447,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.5941956043243408, 0.5941956043243408, 0.594...","[0.739498496055603, 0.739498496055603, 0.73949...","[0.5203070640563965, 0.5203070640563965, 0.520...","[0.45930778980255127, 0.45930778980255127, 0.4...","[0.44315385818481445, 0.443146675825119, 0.443...",[1.0],0,1,NaN
233,118,555,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.5425879955291748, 0.5425879955291748, 0.542...","[0.532169759273529, 0.532169759273529, 0.53216...","[0.5576061010360718, 0.5576061010360718, 0.557...","[0.4346829950809479, 0.4346829950809479, 0.434...","[0.44313791394233704, 0.4431315064430237, 0.44...",[1.0],1,1,"[20, 22, 23, 25]"
234,18,120,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.4509989619255066, 0.4509989619255066, 0.450...","[0.6773908734321594, 0.6773908734321594, 0.677...","[0.3191322088241577, 0.3191322088241577, 0.319...","[0.44336268305778503, 0.44336268305778503, 0.4...","[0.44326716661453247, 0.4432499408721924, 0.44...",[1.0],1,1,[58]

In [12]:
data_item.isnull().sum()

student_id         0
item_id            0
Q_matrix           0
t_all              0
t_e                0
t_s                0
s_e                0
diff               0
evaluate           0
correct            0
pred               0
knowledge_code    59
dtype: int64

In [13]:
data_item=data_item.dropna(axis=0,how='any')
data_item

,student_id,item_id,Q_matrix,t_all,t_e,t_s,s_e,diff,evaluate,correct,pred,knowledge_code
0,96,445,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.18913830816745758, 0.18913830816745758, 0.1...","[0.13853970170021057, 0.13853970170021057, 0.1...","[0.2190929502248764, 0.2190929502248764, 0.219...","[0.1850096434354782, 0.1850096434354782, 0.185...","[0.44314324855804443, 0.44313690066337585, 0.4...",[1.0],0,0,[82]
1,18,114,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.32720625400543213, 0.32720625400543213, 0.3...","[0.3269776999950409, 0.3269776999950409, 0.326...","[0.30763840675354004, 0.30763840675354004, 0.3...","[0.5655176639556885, 0.5655176639556885, 0.565...","[0.4433152973651886, 0.4432937800884247, 0.443...",[1.0],0,0,[58]
2,32,175,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.3055531680583954, 0.3055531680583954, 0.305...","[0.09325031191110611, 0.09325031191110611, 0.0...","[0.42239001393318176, 0.42239001393318176, 0.4...","[0.39525118470191956, 0.39525118470191956, 0.3...","[0.44333550333976746, 0.4433133900165558, 0.44...",[1.0],0,0,"[52, 97]"
3,99,457,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.5710980892181396, 0.5710980892181396, 0.571...","[0.6747953295707703, 0.6747953295707703, 0.674...","[0.5025438070297241, 0.5025438070297241, 0.502...","[0.6662260293960571, 0.6662260293960571, 0.666...","[0.44324880838394165, 0.4432337284088135, 0.44...",[1.0],1,1,"[151, 152]"
4,106,483,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.3991096019744873, 0.3991096019744873, 0.399...","[0.15492047369480133, 0.15492047369480133, 0.1...","[0.5391915440559387, 0.5391915440559387, 0.539...","[0.4333671033382416, 0.4333671033382416, 0.433...","[0.44319283962249756, 0.4431827664375305, 0.44...",[1.0],0,1,"[78, 79]"
...,...,...,...,...,...,...,...,...,...,...,...,...
228,50,236,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.3613055348396301, 0.3613055348396301, 0.361...","[0.1412123441696167, 0.1412123441696167, 0.141...","[0.4841448962688446, 0.4841448962688446, 0.484...","[0.43354663252830505, 0.43354663252830505, 0.4...","[0.4434291422367096, 0.44339820742607117, 0.44...",[1.0],1,0,"[4, 113, 114, 115]"
229,12,83,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.19334465265274048, 0.19334465265274048, 0.1...","[0.17662496864795685, 0.17662496864795685, 0.1...","[0.2000349909067154, 0.2000349909067154, 0.200...","[0.23078209161758423, 0.23078209161758423, 0.2...","[0.4432440400123596, 0.4432295262813568, 0.443...",[1.0],0,0,"[13, 14]"
231,73,343,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.32341212034225464, 0.32341212034225464, 0.3...","[0.3273879587650299, 0.3273879587650299, 0.327...","[0.3062048852443695, 0.3062048852443695, 0.306...","[0.5034056901931763, 0.5034056901931763, 0.503...","[0.4431690275669098, 0.44315993785858154, 0.44...",[1.0],0,0,"[132, 133, 134]"
233,118,555,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.5425879955291748, 0.5425879955291748, 0.542...","[0.532169759273529, 0.532169759273529, 0.53216...","[0.5576061010360718, 0.5576061010360718, 0.557...","[0.4346829950809479, 0.4346829950809479, 0.434...","[0.44313791394233704, 0.4431315064430237, 0.44...",[1.0],1,1,"[20, 22, 23, 25]"
234,18,120,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.4509989619255066, 0.4509989619255066, 0.450...","[0.6773908734321594, 0.6773908734321594, 0.677...","[0.3191322088241577, 0.3191322088241577, 0.319...","[0.44336268305778503, 0.44336268305778503, 0.4...","[0.44326716661453247, 0.4432499408721924, 0.44...",[1.0],1,1,[58]

In [20]:
data_DOA=data_item[['student_id','item_id','knowledge_code','correct']]
data_DOA

     student_id  item_id      knowledge_code  correct
0            96      445                [82]        0
1            18      114                [58]        0
2            32      175            [52, 97]        0
3            99      457          [151, 152]        1
4           106      483            [78, 79]        0
..          ...      ...                 ...      ...
228          50      236  [4, 113, 114, 115]        1
229          12       83            [13, 14]        0
231          73      343     [132, 133, 134]        0
233         118      555    [20, 22, 23, 25]        1
234          18      120                [58]        1

[176 rows x 4 columns]

In [17]:

import json
from collections import defaultdict

In [23]:
import pandas as pd
import json
from collections import defaultdict



# 处理数据
import ast

# 如果 knowledge_code 是字符串，需要转换为列表
data_DOA["knowledge_code"] = data_DOA["knowledge_code"].apply(
    lambda x: ast.literal_eval(x) if isinstance(x, str) else x
)

result = defaultdict(lambda: defaultdict(list))

for _, row in data_DOA.iterrows():
    for code in row["knowledge_code"]:
        # 按照 knowledge_code 和 item_id 分组
        result[code][row["item_id"]].append({
            "user_id": row["student_id"],
            "score": row["correct"],
        })

# 构造目标 JSON 格式
json_result = []
for knowledge_code, exercises in result.items():
    exercises_list = []
    for exer_id, logs in exercises.items():
        exercises_list.append({
            "exer_id": exer_id,
            "logs": logs
        })
    json_result.append({
        "knowledge_code": knowledge_code,
        "exercises": exercises_list
    })

# 输出结果
with open("output.json", "w", encoding="utf-8") as f:
    json.dump(json_result, f, ensure_ascii=False, indent=4)

print("JSON 数据已保存到 output.json 文件中")

JSON 数据已保存到 output.json 文件中

/tmp/ipykernel_873391/2113116671.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_DOA["knowledge_code"] = data_DOA["knowledge_code"].apply(

In [ ]:
import torch
import torch.nn as nn
import torch.nn.functional as F

class CustomModel(nn.Module):
    def __init__(self, input_dim, output_dim):
        super(CustomModel, self).__init__()
        self.input_dim = input_dim
        self.output_dim = output_dim
        # 定义卷积层，降维到 output_dim
        self.conv = nn.Conv1d(
            in_channels=1, 
            out_channels=output_dim, 
            kernel_size=1
        )

    def forward(self, x, input_knowledge):
        # 输入形状: [batch_size, input_dim]
        batch_size, input_dim = x.shape
        assert input_dim == self.input_dim, f"Expected input_dim={self.input_dim}, got {input_dim}"

        # Step 1: 降维
        x = x.unsqueeze(1)  # 添加通道维度，形状 [batch_size, 1, input_dim]
        x = self.conv(x)  # 卷积，形状 [batch_size, output_dim, input_dim]
        x = x.squeeze(2)  # 去掉多余维度，形状 [batch_size, output_dim]

        assert x.shape[1] == self.output_dim, (
            f"Expected output_dim={self.output_dim}, got {x.shape[1]}"
        )

        # Step 2: Softmax
        x_softmax = F.softmax(x, dim=-1)  # [batch_size, output_dim]

        # Step 3: 找出每行最大值的两个维度
        topk_values, topk_indices = torch.topk(x_softmax, 2, dim=-1)  # [batch_size, 2]

        # 确保 topk_indices 不超出范围
        assert torch.max(topk_indices) < self.output_dim, (
            f"Index out of bounds: max(topk_indices)={torch.max(topk_indices)}, "
            f"output_dim={self.output_dim}"
        )

        mask = torch.zeros_like(x_softmax)  # 初始化掩码
        mask.scatter_(1, topk_indices, 1)  # 在掩码中设置前两大值的位置为 1

        # Step 4: 合并 softmax mask 和 input_knowledge
        assert input_knowledge.shape == mask.shape, (
            f"input_knowledge shape {input_knowledge.shape} does not match mask shape {mask.shape}"
        )
        merged = torch.logical_or(mask.bool(), input_knowledge.bool()).float()  # 合并掩码

        # Step 5: 对合并后的结果进行归一化
        normalized = F.normalize(merged, p=2, dim=1)  # L2 范数归一化

        return normalized


# 测试代码
batch_size = 32
input_dim = 4096  # 输入维度
output_dim = 100  # 降维后的 k
input_tensor = torch.randn(batch_size, input_dim)  # 输入向量 [batch_size, input_dim]
input_knowledge = torch.randint(0, 2, (batch_size, output_dim)).float()  # 模拟 one-hot 向量 [batch_size, output_dim]

model = CustomModel(input_dim, output_dim)
output = model(input_tensor, input_knowledge)

print("Output shape:", output.shape)  # 应为 [batch_size, output_dim]
print(output)